accounts:
  - name: alice
    coins: ["200000000stake"]
  - name: relayer
    addresses: "<relayer-address>"
    coins: ["200000000stake"]

validator:
  name: alice
  staked: "100000000stake"

init:
  home: "~/.icq-1"

genesis:
  chain-id: "icq-1"
  
host:
  rpc: "26657"
  p2p: "26658"
  prof: "6060"
  grpc: "9091"
  api: "1337"